language: node_js
node_js: node
cache: yarn
services: docker

before_install:
  - yarn global add greenkeeper-lockfile@1
  - pip install docker-compose

before_script: greenkeeper-lockfile-update

script:
  - docker-compose -f docker-compose-tests.yml build test-ci
  - docker-compose -f docker-compose-tests.yml run test-ci

after_script:
  - docker-compose -f docker-compose-tests.yml down -v

after_success:
  - bash ./scripts/ci-deployment/deploy.sh
