version: '2'
services:
  pharma-etl:
    image: nhsuk/pharmacy-data-etl:${DOCKER_IMAGE_TAG}
    environment:
      AZURE_STORAGE_CONNECTION_STRING: ${AZURE_STORAGE_CONNECTION_STRING}
      CONTAINER_NAME: ${CONTAINER_NAME}
      SYNDICATION_API_KEY: ${SYNDICATION_API_KEY}
      DISABLE_SCHEDULER: ${DISABLE_SCHEDULER}
      ETL_SCHEDULE: ${ETL_SCHEDULE}
      NODE_ENV: production
    labels:
      io.rancher.container.pull_image: always
    logging:
      driver: splunk
      options:
        splunk-url: ${SPLUNK_HEC_URL}
        splunk-token: ${SPLUNK_HEC_TOKEN}
        splunk-insecureskipverify: "true"
        splunk-sourcetype: docker
        splunk-source: pharmacy-data-etl
        splunk-verify-connection: "false"
        tag: "{{`{{.ImageName}} {{.Name}} {{.FullID}}`}}"
        splunk-format: json
