version: '2'

services:
  etl:
    scale: 1
    start_on_create: true
    health_check:
      response_timeout: 60000
      healthy_threshold: 2
      unhealthy_threshold: 3
      initializing_timeout: 60000
      interval: 20000
      strategy: recreate
      request_line: ''
      reinitializing_timeout: 60000
