#!/bin/bash
docker-compose -p test-ci -f docker-compose-tests.yml down -v
docker-compose -p test-ci -f docker-compose-tests.yml build test-ci
docker-compose -p test-ci -f docker-compose-tests.yml run test-ci
